# https://github.com/secureCodeBox/secureCodeBox/blob/main/demo-targets/juice-shop/values.yaml
replicaCount: 1

# -- Define imagePullSecrets when a private registry is used (see: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/)
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

# -- add custom environment variables to the juice-shop container
# ref: https://pwning.owasp-juice.shop/part1/customization.html
containerEnv:
  []
  # - name: NODE_ENV
  #   value: bodgeit

# -- When set, passes in the custom configuration specified below and sets NODE_ENV accordingly
# ref: https://pwning.owasp-juice.shop/part1/customization.html
customConfig:
  # NOTE: Ensure that all required keys are passed, otherwise startup will fail
  # for example `Error: Configuration property "application.chatBot.trainingData" is not defined`
  # ref: https://github.com/juice-shop/juice-shop/blob/master/config/default.yml
  # server:
  #   port: 3000
  #   basePath: ''
  # application:
  #   domain: juice-sh.op
  #   name: 'OWASP Juice Shop'

# -- add labels to the deployment, service and pods
labels: {}

# -- add annotations to the deployment, service and pods
annotations: {}

podSecurityContext:
  {}
  # fsGroup: 2000

securityContext:
  {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: ${juiceshopPort}

ingress:
  enabled: false
  annotations:
    {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
