apiVersion: v1
kind: PersistentVolume
metadata:
 name: pv-sp-0
spec:
 capacity:
   storage: 150Gi
 volumeMode: Filesystem
 accessModes:
 - ReadWriteOnce
 persistentVolumeReclaimPolicy: Retain
 claimRef:
   namespace: splunk
   name: splunk-operator-app-download
 storageClassName: gp2
 local:
   path: /mnt
 nodeAffinity:
   required:
     nodeSelectorTerms:
     - matchExpressions:
       - key: kubernetes.io/hostname
         operator: In
         values:
         - ip-10-0-12-111.ec2.internal
