global:
  kspm:
    deploy: true
agent:
  sysdig:
    settings:
      collector_port: 6443
nodeAnalyzer:
  nodeAnalyzer:
    benchmarkRunner:
      deploy: true
    hostScanner:
      deploy: true
  secure:
    vulnerabilityManagement:
      newEngineOnly: true
